general:
  device: cpu
  seed: 2026
  complete_verifier: bab
  results_file: ../../verification/results/audio_cresnet5_out.pkl

model:
  name: Customized("abcrown_audio.py", "audio_cresnet5", num_classes=10, in_planes=8)
  path: ${CONFIG_PATH}/../model/AudioCResNet5_abcrown.pt

data:
  dataset: Customized("abcrown_audio.py", "speech_commands_fixture")
  num_outputs: 10
  start: 0
  end: 20

specification:
  type: lp
  norm: .inf
  epsilon: 0.007
  robustness_type: verified-acc

attack:
  pgd_order: skip

solver:
  batch_size: 32
  alpha-crown:
    iteration: 10
  beta-crown:
    iteration: 5

bab:
  timeout: 20
  branching:
    method: kfsb
    candidates: 3
